### ISSUE TITLE
Элементы карты выходят за пределы

### ISSUE THREAD

**Issue by ungarson** [avto-dev/bank-card-vue-component#30]
Элементы карты выходят за пределы из-за некорректного box-sizing. 
Сейчас выглядит вот так:
<img width="815" alt="Screenshot 2020-10-22 at 15 50 04" src="https://user-images.githubusercontent.com/13982759/96873986-4ae6b300-147e-11eb-92ac-3fd5509d12ba.png">
Добавьте `box-sizing: border-box !important` для `.card-inner` и то же самое для `.card__field`
Будет выглядеть вот так:
<img width="815" alt="Screenshot 2020-10-22 at 15 50 34" src="https://user-images.githubusercontent.com/13982759/96874020-55a14800-147e-11eb-8f45-6a317ea03a41.png">
Спасибо.

**Comment by gnklv** [comment]
Привет.
Спасибо за issue. Приняли во внимание.
В ближайших релизах это исправится.
