### ISSUE TITLE
Сохранить по нажатию на кнопку

### ISSUE THREAD

**Issue by ungarson** [avto-dev/bank-card-vue-component#31]
Я вижу, что сейчас сохранение доступно только по нажатию на Enter, и чтоб реализовать сохранение по кнопке (это обычный способ!) нужно костыли писать 😔
Можно ли как-нибудь получать введенные данные, чтобы я у себя их сохранял и при дальнейшем нажатию на какую-то определенную кнопку, эти данные отправлялись? Ну или если возможно, чтобы я просто использовал вами написанную кнопку, которую можно либо показывать, либо не показывать.

**Comment by gnklv** [comment]
На данный момент нет функционала, позволяющего получить данные карты из компонента.

Единственное, что могу предложить, это селектить DOM-элементы полей карты и брать `value`.
```
const cardNumber = document.querySelector('[data-cp="cardNumber"]').value;
const month = document.querySelector('[data-cp="expDateMonth"]').value;
const year = document.querySelector('[data-cp="expDateYear"]').value;
const cvv = document.querySelector('[data-cp="cvv"]').value;
```

**Comment by ungarson** [comment]
@gnklv так и сделал, спасибо
