### ISSUE TITLE
Cardholder

### ISSUE THREAD

**Issue by ungarson** [avto-dev/bank-card-vue-component#32]
Добавьте поле для владельца карты, пожалуйста 🙂

**Comment by gnklv** [comment]
@ungarson 
К сожалению, пока UI не готов к тому, чтобы добавить в него поле с владельцем карты. Необходимо будет внести большие корректировки.
Радует, что для платежных систем можно обойтись без поля владельца карты

**Comment by ungarson** [comment]
@gnklv в cloudpayments он нужен :(
Но ок, я вас понял. 
Спасибо за то, что уделили время.

**Comment by gnklv** [comment]
@ungarson как раз для cloudpayments у нас есть заглушка для имени - 'CARHOLDER NAME'. И ее также можно взять из инпута 'document.querySelector('[data-cp="name"]').value
