### ISSUE TITLE
Что значит `[NO OWNER]` в описании репозитория?

### ISSUE THREAD

**Issue by gomzyakov** [avto-dev/bank-card-vue-component#86]
<img width="493" alt="image" src="https://user-images.githubusercontent.com/1460709/210035041-067dd0c8-7335-4f3d-8ba0-b0315b64f00c.png">

**Comment by jetexe** [comment]
Это значит, что никто не занимается поддержкой и развитием пакета на постоянной основе

**Comment by gomzyakov** [comment]
@jetexe спасибо)
